name: ci

on:
    push:
        braches: master

jobs:
    main:
        runs-on: ubuntu-latest
        steps:
            - name: Getting Update
              run: sudo apt-get update
            - name: Installing Python
              run: sudo apt-get install python3.6
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Login to Dockerhub
              uses: docker/login-action@v1
              with:
                  username: ${{secrets.DOCKERHUB_USERNAME}}
                  password: ${{secrets.DOCKERHUB_PASSWORD}}
            - name: Build and Push
              id: docker_build
              uses: docker/build-push-action@v2
              with:
                  push: true
                  tags: 20544dk/davidprivate:blog_node
            - name: Image digest
              run: echo ${{steps.docker_build.ouputs.digest}}
